### ISSUE TITLE
Show Full Playlist

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/wxyc-ios-64#10]
There should be a way for a user to see all of the songs that the DJ played on their show. Probably key decisions here are:

How far back should we go?
What should we display?

My suggestion would be to just show playcuts from the current show, but that may be a bit harder since the playlist isn't really organized by show. Alternatively, 2/3 hours seems fine.

I prefer my playlists minimal, without album art (since it just makes it a bit hard to quickly scroll through to find something)... here's a screenshot from WFMU's playlist in their app for some minimalist inspiration.

![img_9efa162a0cca-1](https://user-images.githubusercontent.com/1800276/32928769-af8557fc-cb21-11e7-9304-dd5464bd1c39.jpeg)

**Comment by swardlincoln** [comment]
I like the minimalist look. I think 2 hours back would be fine. Maybe even 1.5 hours. In my personal experience I have never needed anymore than 2 hours back. 
I like the format of the WXDU listings: Song/Artist/Album

**Comment by jakebromberg** [comment]
I'm still not convinced that people want a playlist feature. Sharing and favoring are more important and have less design costs.

**Comment by swardlincoln** [comment]
I would agree with @jakebromberg  except that there have been times when I'm in my car listening to the station, I hear a song I like, and I have no way to find out what it was. If I listen long enough the DJ will announce it, but often - on the old app - I would look back at the play history to find out. This is a rare case of course. One that would be remedied if that information showed up my car radio display. However, if you think the design cost would be too high then it might not be worth it.

**Comment by jakebromberg** [comment]
I would just like for us to think carefully about this first. The current paginated view that we have would have to change somehow if we were to represent the playlist in a vertical scroll view. I could run some experiments. I'm not opposed to showing a playlist, but I think this should rank lower than other features on the table.

**Comment by dvdokkum** [comment]
shipped in 2.2
