### ISSUE TITLE
Add some buffering logic to the audio streaming

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/wxyc-ios-64#12]
The current streaming is fairly naive in its implementation, which can result in the stream dropping fairly often (it reconnects after a second or two, but can be an annoying listening experience). Probably the right way to handle this is to load a buffer when connecting to the live stream. There may be some built-in options for handling this in AVPlayer but I haven't explored them. 

Some radio streaming apps allow the user to set their preferred buffer duration as a setting, which is a nice approach but perhaps not really worth the effort.

**Comment by swardlincoln** [comment]
If we let the user set the buffer and they max it out it might take some time while the player is buffering for stream to start, right? Would this ruin the user experience?

**Comment by dvdokkum** [comment]
not necessarily? we'd just show a buffering status and maybe a % buffering
thing. i think the wfmu app handles this nicely... i have my buffer set to
max b/c i tend to walk around the city a bunch while listening. but... not
sure how important this one is.

**Comment by jakebromberg** [comment]
We might be able to set a buffer on the streaming unit inside the station. It would burst down the data on initial load and then stream at a real-time rate thereafter.

**Comment by dvdokkum** [comment]
haven't had any buffering related issues in practice. closing this.
