### ISSUE TITLE
Explore Using Spotify API for Album Art 

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/wxyc-ios-64#13]
We currently attempt to get album art from LastFM, then fallback on iTunes. iTunes tends to have better coverage, but they only offer low res (100x100) images. Spotify has public APIs for this, I just haven't explored using them here.

**Comment by jakebromberg** [comment]
I looked into this. This would require the user logging into a Spotify account.

**Comment by dvdokkum** [comment]
Yeah.... I thought it was public (no login required) but it does appear to require authentication now. I think if we did this we'd want to make it a larger Spotify integration. A user could auth into their Spotify account in order to get high-res album and to save a track from the playlist directly to their Spotify library.

**Comment by dvdokkum** [comment]
They have an iOS sdk in beta if we ever want to do this: https://developer.spotify.com/technologies/spotify-ios-sdk/

**Comment by jakebromberg** [comment]
We can get larger images from the last.fm API than what they give us. We
just have to munge the URLs.

**Comment by jakebromberg** [comment]
I'll look into the Spotify SDK.

**Comment by jakebromberg** [comment]
Looks like the SDK still requires a user to log in first.
https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/
We might want to think about tapping into Spotify and Apple Music for
favoriting

**Comment by dvdokkum** [comment]
latest (2.2) shipped with a different album art engine that is good.
