### ISSUE TITLE
Is there a way to recover favorite tracks from the old app?

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/wxyc-ios-64#16]
So far we've had a single user ask if there's a way to recover their old faves list. Is that even possible?

**Comment by jakebromberg** [comment]
Good question. We still have the `momd` file from the old repo lying around. The test would be to install the old app, add some favorites, and then install the new app to see if the database still exists. I'll quickly add that Core Data is an [enormous pain in the ass](http://nshipster.com/nscoding/) and I disown any features related to it.

**Comment by dvdokkum** [comment]
How do you check if the database still exists?

**Comment by jakebromberg** [comment]
You should do all this in the simulator. The app bundle will get copied to
a location on your file system. Inspect the contents of the bundle.

**Comment by jakebromberg** [comment]
I really don't think we should support favorites in the app the way we used to. Many versatile sharing services that include bookmarking features exist. We should focus on developing a sharing flow.

**Comment by dvdokkum** [comment]
the answer is no and we're now letting folks export out of the app rather than create a native list of favorites.
