### ISSUE TITLE
Show a graphic visualizer instead of volume control

### ISSUE THREAD

**Issue by jakebromberg** [WXYC/wxyc-ios-64#18]
The volume control is a waste of space since people can adjust that from the hardware buttons. Instead, let's give the app some personality and make a nice multiband graphic visualizer. I've already done some research into using Audio Units and feeding raw uncompressed audio data into an AUGraph and getting values out by applying a transform

**Comment by dvdokkum** [comment]
Alright, up to you how to implement this, but just a heads up that the volume control is currently broken from your other change (swiping right to get to the info screen) so we should either kill it entirely or fix (for now).

**Comment by dvdokkum** [comment]
volume control was killed long ago
