### ISSUE TITLE
Add share functionality

### ISSUE THREAD

**Issue by jakebromberg** [WXYC/wxyc-ios-64#34]
There's code in the app to do this, but we don't surface any UI element. We should think about this as not just sharing to Facebook, but also to bookmarking services like Pinterest (list your services below). 

The existing logic is something like "I'm listening to [college radio track] on WXYC" but we need to anticipate more use cases than that, possibly switch strings or metadata based on the service we're sharing to.

**Comment by dvdokkum** [comment]
shipped in 2.2
