### ISSUE TITLE
Reimplement Sevice/Model layer using Combine

### ISSUE THREAD

**Issue by jakebromberg** [WXYC/wxyc-ios-64#59]
Apple announced a new framework at WWDC this year, [Combine](https://developer.apple.com/documentation/combine), that largely obsoletes my home brewed Future/Promise data types in the app. Nothing gives me greater pleasure than [setting fire to dead code](https://github.com/WXYC/wxyc-iphone-app/commit/9190cd90aa0eb5cf9d5282052816eb9e8e6a97f8).

**Comment by dvdokkum** [comment]
Done in 2.3
